[Eth]
NetworkId = 1012
SyncMode = "full"
LightPeers = 100
DatabaseCache = 768
EnablePreimageRecording = false

[Eth.Miner]
GasPrice = 500000000000000

[Eth.TxPool]
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 300000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 4096
GlobalSlots = 16384
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01

[Node]
DataDir = "/data/newchain/mainnet/nodedata"
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8808
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "txpool", "net"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = ["enode://503ad5186aba1a72e727afba9234fa785cf207eb9e21182c35e83f2d0cd342366edce7eb711ddbdbdaa99356eaf9ff0a90139119d06e463a55777076fb6ee8f4@47.57.101.140:38311", "enode://e4b028f6c3f8981c37b360451132a830a4308157ed550237751e20d00026f5efecdff209438741fbd015b3aefe119b16cbd5840620caf9bf2f7ac941aa1ff649@54.249.167.30:38311", "enode://bd2672d9ef15e2e882d4e64dd938d5c336d06800c7242d15ac037f645f1256598ecf6549415c58f5afe647b283b5f8b76fc3235a3e61c143f947b39d8523469c@138.91.12.246:38311"]
BootstrapNodesV5 = ["enode://503ad5186aba1a72e727afba9234fa785cf207eb9e21182c35e83f2d0cd342366edce7eb711ddbdbdaa99356eaf9ff0a90139119d06e463a55777076fb6ee8f4@47.57.101.140:38311", "enode://e4b028f6c3f8981c37b360451132a830a4308157ed550237751e20d00026f5efecdff209438741fbd015b3aefe119b16cbd5840620caf9bf2f7ac941aa1ff649@54.249.167.30:38311", "enode://bd2672d9ef15e2e882d4e64dd938d5c336d06800c7242d15ac037f645f1256598ecf6549415c58f5afe647b283b5f8b76fc3235a3e61c143f947b39d8523469c@138.91.12.246:38311"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":38311"
EnableMsgEvents = false
