[Eth]
NetworkId = 1012
SyncMode = "full"
DiscoveryURLs = []
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
DatabaseCache = 768
DatabaseFreezer = ""
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""
RPCGasCap = 0
RPCTxFeeCap = 0e+00

[Eth.Miner]
GasFloor = 100000000
GasCeil = 8000000
GasPrice = 500000000000000
Recommit = 3000000000
Noverify = false

[Eth.TxPool]
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 300000000000
PriceLimit = 500000000000000
PriceBump = 10
AccountSlots = 4096
GlobalSlots = 16384
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01

[Node]
DataDir = "/data/newchain/mainnet/nodedata"
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
HTTPPort = 8808
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "txpool", "net"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = ["enode://503ad5186aba1a72e727afba9234fa785cf207eb9e21182c35e83f2d0cd342366edce7eb711ddbdbdaa99356eaf9ff0a90139119d06e463a55777076fb6ee8f4@47.57.101.140:38311", "enode://6993a82d7eec6ce031723638012d0c586f59a31f3c7cb9dd3407303ae9499b7d242b3e8641b15bfd11fafc4d465d9670125aa1965d799312c81f8a743727e725@18.140.251.161:38311", "enode://2a2b67eabc43244234d6c7b16e79970da8970368ef5cf550ef278fc62860fddb596c52587f9cc39c3173ecfb4e3cff207c1fd79e9aa581127b66ec93da4f1b94@54.250.75.220:38311"]
BootstrapNodesV5 = ["enode://503ad5186aba1a72e727afba9234fa785cf207eb9e21182c35e83f2d0cd342366edce7eb711ddbdbdaa99356eaf9ff0a90139119d06e463a55777076fb6ee8f4@47.57.101.140:38311", "enode://6993a82d7eec6ce031723638012d0c586f59a31f3c7cb9dd3407303ae9499b7d242b3e8641b15bfd11fafc4d465d9670125aa1965d799312c81f8a743727e725@18.140.251.161:38311", "enode://2a2b67eabc43244234d6c7b16e79970da8970368ef5cf550ef278fc62860fddb596c52587f9cc39c3173ecfb4e3cff207c1fd79e9aa581127b66ec93da4f1b94@54.250.75.220:38311"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":38311"
EnableMsgEvents = false
